language: elixir
elixir:
  - 1.5.2
otp_release:
  - 19.0
addons:
  postgresql: '9.6'
services:
  - postgresql
before_install:
  - cp config/test.travis.exs config/test.secret.exs
  - cp config/dev.travis.exs config/dev.secret.exs
before_script:
  - mix do ecto.create, ecto.migrate
script:
  - mix test --exclude integration
